# Imports

In [8]:
import torch


# Intro

## testing

In [9]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4216, 0.0691, 0.2332],
        [0.4047, 0.2162, 0.9927],
        [0.4128, 0.5938, 0.6128],
        [0.1519, 0.0453, 0.5035],
        [0.9978, 0.3884, 0.6929]])


## is gpu available

In [10]:
torch.cuda.is_available()

True

In [11]:
# random zeros
z = torch.zeros((5,3))
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [12]:
# testing seed 
torch.manual_seed(1729)
r1 = torch.rand((2,2))

r2= torch.rand((2,2))

torch.manual_seed(1729)
r3 = torch.rand((2,2))

print(f'{r1} \n\n{r2} \n\n{r3}')

tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]]) 

tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]]) 

tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


In [ ]:
# simple tensor arithmatic

# create all ones
ones = torch.ones((2,3))

#multiple by a scalar, 2
twos = ones * 2

# add two tensors of the same shape
threes = ones + twos

print(f"{ones}\n\n{twos}\n\n{threes}")

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[2., 2., 2.],
        [2., 2., 2.]])

tensor([[3., 3., 3.],
        [3., 3., 3.]])


# Assignment 1
Simple Neural Network

https://www.youtube.com/watch?v=IC0_FRiX-sw&list=PL_lsbAsL_o2CTlGHgMxNrKhzP97BaG9ZN&index=1&t=329s

In [20]:
import torch
import torch.nn as nn # for torch.nn.Module, the parent object for Pytorch models
import torch.nn.functional as F # for the activation function